plugins:
  - jekyll-sitemap
  - jekyll-remote-theme # add this line to the plugins list if you already have one
# google_analytics: G-14BR8NWGGQ
gtag: G-14BR8NWGGQ

# remote_theme: pages-themes/architect@v0.2.0
# remote_theme: jekyll-theme-minimal
# remote_theme: mmistakes/jekyll-theme-basically-basic
# remote_theme: "jeffreytse/jekyll-theme-yat"
remote_theme: daattali/beautiful-jekyll@6.0.1
# remote_theme: pages-themes/cayman@v0.2.0
# remote_theme: mmistakes/minimal-mistakes
# remote_theme: poole/hyde
# remote_theme: poole/lanyon
# remote_theme: leakyabstractions/pretty-docs
# remote_theme: emilbaehr/automatic-app-landing-page


title: [技術メモ]
description: [Umm...]

markdown: CommonMarkGhPages
commonmark:
  extensions:
    - autolink
    - strikethrough
    - table
    - footnotes
    - tasklist
    - shortcodes
    - superscript
    - description_lists
